### ISSUE TITLE
I need help understanding this. I get a pooling error when I click the save video button

### ISSUE THREAD

**Issue by Mia112** [Mia112/Video-Player#20]
index.js:1 Warning: This synthetic event is reused for performance reasons. If you're seeing this, you're accessing the method `movementX` on a released/nullified synthetic event. This is a no-op function. If you must keep the original synthetic event around, use event.persist(). See https://fb.me/react-event-pooling for more information.

**Comment by emerzonic** [comment]
I think this has been resolved
